/**
 * Created with template on 1/26/18.
 */
export const LANDING_SUBMIT_FORM = "LANDING_SUBMIT_FORM";
export const LANDING_CHANGE_ROOM_NUMBER = "LANDING_CHANGE_ROOM_NUMBER";
export const LANDING_CHANGE_USER_NAME = "LANDING_CHANGE_USER_NAME";

export const CHATTING_GET_ROOM_INFO = "CHATTING_GET_ROOM_INFO";
export const CHATTING_ROOM_INFO = "CHATTING_ROOM_INFO";
export const CHATTING_GUEST_JOIN = "CHATTING_GUEST_JOIN";
export const CHATTING_GUEST_LEAVE = "CHATTING_GUEST_LEAVE";
export const CHATTING_INPUT_MESSAGE = "CHATTING_INPUT_MESSAGE";
export const CHATTING_START_CALL = "CHATTING_START_CALL";
export const CHATTING_ANSWER_CALL = "CHATTING_ANSER_CALL";
export const CHATTING_START_VIDEO_CALL = "CHATTING_START_VIDEO_CALL";
export const CHATTING_SEND_MESSAGE = "CHATTING_SEND_MESSAGE";
export const CHATTING_RTC_SETUP = "CHATTING_RTC_SETUP";

export const ON_ERROR = "ON_ERROR";

export const SOCKET_ENTER_ROOM = "SOCKET_ENTER_ROOM";
export const SOCKET_ERROR = "SOCKET_ERROR";
export const SOCKET_USER_DISCONNECTED = "SOCKET_USER_DISCONNECTED";
export const SOCKET_GET_ROOM_INFO = "SOCKET_GET_ROOM_INFO";
export const SOCKET_SEND_ROOM_INFO = "SOCKET_SEND_ROOM_INFO";
export const SOCKET_ROOM_INFO = "SOCKET_ROOM_INFO";

export const RTC_RECEIVE_MESSAGE = "RTC_RECEIVE_MESSAGE";
export const RTC_ON_ADD_STREAM = "RTC_ON_ADD_STREAM";
export const RTC_START_STREAM = "RTC_START_STREAM";