/**
 * Created with template on 1/26/18.
 */
export const LANDING_SUBMIT_FORM = "LANDING_SUBMIT_FORM";
export const LANDING_CHANGE_ROOM_NUMBER = "LANDING_CHANGE_ROOM_NUMBER";
export const LANDING_CHANGE_USER_NAME = "LANDING_CHANGE_USER_NAME";

export const ON_ERROR = "ON_ERROR";


export const SOCKET_ENTER_ROOM = "SOCKET_ENTER_ROOM";
export const SOCKET_ERROR = "SOCKET_ERROR";
export const SOCKET_DISCONNECT = "SOCKET_DISCONNECTED";